openapi: 3.0.0
info:
  version: 1.0.0
  title: chroner
  description:  Chroner API, provides resources need to mainetenance  chroner APIs

servers:
  - url: http://localhost:5000/api/v1
    description: API
paths:
  /crons:
    get:
      summary: Retrive all crons in use
      decription:
      responses:
        '201':
          description: 'OK'
        '401':
          description: 'Elements not found'

  /create_cron:
    post:
      summary: Dreates cron job from parameter
      responses:
        '201':
          description: OK
        '500':
          description: 'Cron already exists'
        '501':
          description: 'Can not create cron'
  /delete_cron:
    post:
      summary: Deletes cron defined in parameter
      responses:
        '201':
          description: OK
        '500':
          description: 'Cron does not exist'
        '501':
          description: 'Can not delete cron'

#components:
#  securitySchemes:
#    bearerAuth:            # arbitrary name for the security scheme
#      type: http
#      scheme: bearer
#      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
# 2) Apply the security globally to all operations
#security:
#  - bearerAuth: []         # use the same name as above


